server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true # 소스파일에 변화가 있을 때 자동으로 서버 재 시작 설정
    livereload:
      enabled: true # 정적 리소스에 변화가 있을 때 바로 반영한다.
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    include: oracle, oauth, email, s3 # include application-oracle.yml (오라클 접속정보 숨김)
    # include oauth, email 를 통해 application-oauth & email 정보를 숨긴다

  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update # create -- 서버 restart시 table정보가 reset 됨
      # 로컬에서 초기 개발시 사용. 일반적으로는 none옵션 권장
    show-sql: true
    properties:
      hibernate.format_sql: true

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


---
spring:
  profiles:
    include: key



oldUrl: https://indiebucket.s3.ap-northeast-2.amazonaws.com/tempImg
newUrl: https://indiebucket.s3.ap-northeast-2.amazonaws.com/img


