# email 인증 용도의 application 파일
spring :
  mail:
    host: smtp.gmail.com
    port: 587
    username: ojlee6207@gmail.com
    password: erpn qgpc nkgf nosv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
    auth-code-expiration-millis: 180000
