INSERT INTO USER_ROLE VALUES(1, '관리자');
INSERT INTO USER_ROLE VALUES(2, '일반');
INSERT INTO USER_ROLE VALUES(3, '아티스트');

INSERT INTO FUND_TYPE VALUES(1, '공연');
INSERT INTO FUND_TYPE VALUES(2, '앨범');
INSERT INTO FUND_TYPE VALUES(3, '굿즈');
INSERT INTO FUND_TYPE VALUES(4, '팬미팅');

INSERT INTO CONTENT_TYPE VALUES(1, '자유');
INSERT INTO CONTENT_TYPE VALUES(2, '자랑');
INSERT INTO CONTENT_TYPE VALUES(3, '콜로세움');
INSERT INTO CONTENT_TYPE VALUES(4, '전용');

INSERT INTO REPORT_TYPE VALUES(1, '허위사실');
INSERT INTO REPORT_TYPE VALUES(2, '명예훼손');
INSERT INTO REPORT_TYPE VALUES(3, '욕설');
INSERT INTO REPORT_TYPE VALUES(4, '광고');
INSERT INTO REPORT_TYPE VALUES(5, '기타');

-- 이건 사용 안하는 중